
iden "variable"
abcd 102.23 2054 "245ello" "23far" "choppers" "'{} Enclosed string"

node1 {
	data "riddo" 775
	
	{
		enipt,epin
	}
	
	{
		captain "obvious"
	}
	Epilouge
	"Special identifier name" "Magic."
}

node2 {
	NullStringTest ""
	stuff "goes" "here"
	"Annd now for multi-line strings :)" "okgo" "abcdefg foobar
wakka
end. Note how the white-space after a newline gets removed" "Oh, you can also continue on." 112
}
