
attr value1 "value two! '' lalala {}"

namednode {
	data.zip\\sounds\intro.ogg 0 1 1 2 3 5 8 13
}

{
	namelessnode this,is,sparta!
	echoes "/eval:: a + b / 0.1392"
}
test.some.struff largro(extera)
"White-spaced identifier names" Booyah!

SingleNode {
	First "single line test"
}

{
	Second "single line test" 3.00000000
}

"Node names can also be quoted!" {
	Indeed
}

{
	
	Named {
		Alloc 22
	}
	
	Named2 {
		"Make cookies"
	}
	
	{
		notnamed 84002.0000
	}
}
