
attr "value1" "value two! /'/' lalala {}/>>"

namednode {
	data.zip\\sounds\intro.ogg 0 1 1 2 3 5 8 13
	
}
madness? "das cookie?"

{
	namelessnode "this,is,sparta!"
	echoes "/eval: a + b / 0.1392"
	
}
after "periods.namespaces!"
Lets "Make" "a" "superlong" "SUPER LLONG!!/>>" "identifier" "More... and moreeee" 12145636 463.023865

SingleNode {
	First "single line test"
}

{
	Second "single line test"
}

{
	
	Named {
		Alloc
	}
	
	Named2 {
		Make "blubber"
	}
	
	{
		notnamed
	}
}
