'String test..
attr value1 "value two! '' lalala {}"

namednode { 'Comment after opening node
	data.zip\\sounds\intro.ogg 0 1 1 2 3 5 8 13 ' Comment!
}'Hello!


{'Comment!
	namelessnode this,is,sparta!'No space comment!
	echoes "/e: a + b / 0.1392"
} ' Comment!

test.some.struff largro(extera)
"White-spaced identifier names" "Booyah!"

SingleNode {First "single line test"}
{ Second "single line test" .003 }

"Node names can also be quoted!" {
	Indeed
}

{
	Named { Alloc 22}
	Named2 { "Make cookies"}
	{notnamed 84.002}
}

bools true false true true
