
' No-preceding comment..
iden variable
abcd 102.23 2054 .245ello 23far choppers "'{} Enclosed string"' No-whitespace comment

node1 {
	data riddo 775 ' Whitespace-test comment
	{enipt,epin} ' No-name node test
	' Random comment
	{ captain obvious }
	"Epilouge"
	"Special identifier name" "Magic."
}

node2 {
	NullStringTest ""
	stuff goes here
	"Annd now for multi-line strings :)" okgo "abcdefg foobar
												wakka
												Note how the white-space after a newline gets removed" "Oh, you can also continue on." 112
}
